### ISSUE TITLE
bootstrap_transformations on queries with external table used multiple times

### ISSUE THREAD

**Issue by ynaim94** [harrystech/arthur-redshift-etl#547]
**Describe the bug**
When the query involves an external table twice, `arthur.py bootstrap_transformations` fails because it creates the dependency twice in the produced design file, which fail `table_design.schema` validation.

**To Reproduce**
1. Go to https://github.com/harrystech/harrys-data-warehouse/pull/1795
2. Checkout the branch
3. Run `arthur.py bootstrap_transformations -u CTAS base__retail.daily_retailer_sales__v1`
4. See error:

```
jsonschema.exceptions.ValidationError: ['external__ascendio__exports.daily_retailer_sales__v1', 'external__ascendio__exports.daily_retailer_sales__v1'] has non-unique elements

Failed validating 'uniqueItems' in schema['properties']['depends_on']:
    {'description': 'List of all dependency tables of this transformation',
     'items': {'$ref': '#/definitions/table_name'},
     'minItems': 1,
     'type': 'array',
     'uniqueItems': True}

On instance['depends_on']:
    ['external__ascendio__exports.daily_retailer_sales__v1',
     'external__ascendio__exports.daily_retailer_sales__v1']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/src/arthur-redshift-etl/python/etl/design/load.py", line 108, in validate_table_design_syntax
    etl.config.validate_with_schema(table_design, "table_design.schema")
  File "/opt/src/arthur-redshift-etl/python/etl/config/__init__.py", line 288, in validate_with_schema
    raise SchemaValidationError("failed to validate against '%s'" % schema_name) from exc
etl.errors.SchemaValidationError: failed to validate against 'table_design.schema'
```

**Expected behavior**
The script should infer a single dependence on an external table.

**Comment by thomas-vogels** [comment]
Patch:

```diff
diff --git a/python/etl/design/bootstrap.py b/python/etl/design/bootstrap.py
index 0438337..a9a8a4a 100644
--- a/python/etl/design/bootstrap.py
+++ b/python/etl/design/bootstrap.py
@@ -242,8 +242,8 @@ def search_query_step(line: str) -> Optional[Dict[str, str]]:
 
 def fetch_dependency_hints(cx: Connection, stmt: str) -> Optional[List[str]]:
     """Parse a query plan for hints of which relations we might depend on."""
-    s3_dependencies = []
-    xn_dependencies = []
+    s3_dependencies = set()
+    xn_dependencies = set()
 
     logger.debug("Looking at query plan to find dependencies")
     try:
@@ -257,9 +257,9 @@ def fetch_dependency_hints(cx: Connection, stmt: str) -> Optional[List[str]]:
         if maybe is None:
             continue
         if "s3_table" in maybe:
-            s3_dependencies.append(maybe["s3_table"])
+            s3_dependencies.add(maybe["s3_table"])
         if "xn_table" in maybe:
-            xn_dependencies.append(maybe["xn_table"])
+            xn_dependencies.add(maybe["xn_table"])
 
     if s3_dependencies and xn_dependencies:
         # Unfortunately the tables aren't qualified with a schema so we can't use the info.
```
