### ISSUE TITLE
Upate user command fails

### ISSUE THREAD

**Issue by thomas-vogels** [harrystech/arthur-redshift-etl#672]
**Describe the bug**
Running `update_user` fails with:
```
2022-03-07 21:44:54 - CRITICAL - Something terrible happened:
Traceback (most recent call last):
  File "/opt/src/arthur-redshift-etl/python/etl/commands.py", line 64, in execute_or_bail
    yield
  File "/opt/src/arthur-redshift-etl/python/etl/commands.py", line 175, in run_arg_as_command
    args.func(args)
  File "/opt/src/arthur-redshift-etl/python/etl/commands.py", line 764, in callback
    args.username,
AttributeError: 'Namespace' object has no attribute 'username'
```

**To Reproduce**
Run: `arthur.py update_user --group etl_ro tom`
(You can pick any user name.)

**Expected behavior**
The user should be added to the given group.

**Comment by thomas-vogels** [comment]
fixed
